### ISSUE TITLE
ethrealengine to ir-engine

### ISSUE THREAD

**Issue by Arvrairobo** [ir-engine/ir-engine#418]
what happened and why we need to change the name to IR-Engine? why DMCA notice ? 

i am following ethreal engine since couple of years and i liked that project very much.

is it same license? same free software? or anything changed?

**Comment by HexaField** [comment]
Ethereal Engine was acquired by Infinite Reality earlier this year. We are the same team with the same goal, just now with more resources. The license is the same. 

https://venturebeat.com/games/infinite-reality-acquires-ethereal-engine-for-75m-in-share-deal/

Unfortunately, the acquisition ruffled some feathers, we are dealing with the DMCA. Sorry about it. The full commit history is still in this repo, minus some commits which contained a client's project code that was accidentally committed in 2021, hence the new repository.
